// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/orders/orders_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/orders/orders_repository.go -destination=mocks/order_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	orders "docker-example/internal/app/orders"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockordersRepository is a mock of ordersRepository interface.
type MockordersRepository struct {
	ctrl     *gomock.Controller
	recorder *MockordersRepositoryMockRecorder
}

// MockordersRepositoryMockRecorder is the mock recorder for MockordersRepository.
type MockordersRepositoryMockRecorder struct {
	mock *MockordersRepository
}

// NewMockordersRepository creates a new mock instance.
func NewMockordersRepository(ctrl *gomock.Controller) *MockordersRepository {
	mock := &MockordersRepository{ctrl: ctrl}
	mock.recorder = &MockordersRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockordersRepository) EXPECT() *MockordersRepositoryMockRecorder {
	return m.recorder
}

// getOrderByOrderNumber mocks base method.
func (m *MockordersRepository) getOrderByOrderNumber(ctx context.Context, orderNumber string) (orders.OrdersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getOrderByOrderNumber", ctx, orderNumber)
	ret0, _ := ret[0].(orders.OrdersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getOrderByOrderNumber indicates an expected call of getOrderByOrderNumber.
func (mr *MockordersRepositoryMockRecorder) getOrderByOrderNumber(ctx, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getOrderByOrderNumber", reflect.TypeOf((*MockordersRepository)(nil).getOrderByOrderNumber), ctx, orderNumber)
}
